- name: APIC - Initial Fabric Setup and Best Practice Application
  hosts: dCloud1
  gather_facts: no

  vars:
    aci_login: &aci_login
      hostname: '{{ apic_host }}'
      username: '{{ apic_username }}'
      password: '{{ apic_password }}'
      use_proxy: '{{ apic_use_proxy }}'
      validate_certs: '{{ apic_validate_certs }}'

  tasks:
  - name: Enable MCP on fabric
    aci_rest:
      <<: *aci_login
      path: /api/node/mo/uni/infra/mcpInstP-default.xml
      method: post
      content: '<mcpInstPol adminSt="enabled" annotation="" ctrl="pdu-per-vlan" descr="" dn="uni/infra/mcpInstP-default" initDelayTime="180" loopDetectMult="1" loopProtectAct="port-disable" name="default" nameAlias="" key="{{ dc.mcpKey }}" ownerKey="" ownerTag="" txFreq="2" txFreqMsec="0"/>'
    delegate_to: localhost

  - name: Disable remote EP learn, enforce subnet check, domain validation
    aci_rest:
      <<: *aci_login
      path: /api/node/mo/uni/infra/settings.xml
      method: post
      content: '<infraSetPol enforceSubnetCheck="yes" unicastXrEpLearnDisable="yes" domainValidation="yes"/>'
    delegate_to: localhost

  - name: Enable EP loop protection
    aci_rest:
      <<: *aci_login
      path: /api/node/mo/uni/infra/epLoopProtectP-default.xml
      method: post
      content: '<epLoopProtectP action="" adminSt="enabled" annotation="" loopDetectIntvl="60" loopDetectMult="4" />'
    delegate_to: localhost

  - name: Enable IP aging
    aci_rest:
      <<: *aci_login
      path: /api/node/mo/uni/infra/ipAgingP-default.xml
      method: post
      content: '<epIpAgingP adminSt="enabled"/>'
    delegate_to: localhost

  - name: Enable rogue endpoint detection
    aci_rest:
      <<: *aci_login
      path: /api/node/mo/uni/infra/epCtrlP-default.xml
      method: post
      content: '<epControlP adminSt="enabled" rogueEpDetectIntvl="30" rogueEpDetectMult="6"/>'
    delegate_to: localhost

  - name: Enable port tracking
    aci_rest:
      <<: *aci_login
      path: /api/node/mo/uni/infra/trackEqptFabP-default.xml
      method: post
      content: '<infraPortTrackPol adminSt="on"/>'
    delegate_to: localhost

  - name: Enable strict COOP group policy
    aci_rest:
      <<: *aci_login
      path: /api/node/mo/uni/fabric/pol-default.xml
      method: post
      content: '<coopPol type="strict"/>'
    delegate_to: localhost

  - name: Enable BFD for fabric interfaces
    aci_rest:
      <<: *aci_login
      path: /api/node/mo/uni/fabric/l3IfP-default.xml
      method: post
      content: '<l3IfPol bfdIsis="enabled"/>'
    delegate_to: localhost

  - name: Preserve COS values through fabric
    aci_rest:
      <<: *aci_login
      path: /api/node/mo/uni/infra/qosinst-default.xml
      method: post
      content: '<qosInstPol name="default" ctrl="dot1p-preserve"></qosInstPol>'
    delegate_to: localhost
